#spring:
#  application:
#    name: hr-api-gateway-zuul
#
#  server:
#    port: 8765
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#      spring:
#
#        cloud:
#
#          gateway:
#
#            routes:
#
#              - id: hr-payroll
#
#                uri: lb://hr-payroll/payments
#
#                predicates:
#
#                  - Path=/payments/**
#
#              - id: hr-worker
#
#                uri: lb://hr-worker/workers
#
#                predicates:
#
#                  - Path=/workers/**
